# Generated by Django 5.2.2 on 2025-09-30 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], max_length=10)),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=12)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
                ('usuario_apertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_cierre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
