# Generated by Django 5.2.2 on 2025-09-30 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_cierre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja',
            name='usuario_apertura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caja_apertura', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
