# Generated by Django 5.2.2 on 2025-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_usuario_cierre_alter_caja_usuario_apertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='hora_cierre',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
