# Generated by Django 5.2.2 on 2025-09-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0003_caja_hora_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_hoy', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inicio_mañana', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ventas_dni', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ventas_bna', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_salidas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_retiro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_anulado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
            ],
        ),
    ]
